Falley/Controllers/DutiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.ViewModel.Duties;
using Microsoft.AspNetCore.Mvc;

namespace Falley.Controllers
{
    public class DutiesController : Controller
    {
        private readonly IDutyService _dutyService;
        private readonly IUserContext _userContext;
        public DutiesController(
            IDutyService dutyService, 
            IUserContext userContext)
        {
            _dutyService = dutyService;
            _userContext = userContext;
        }
        public IActionResult Create(Guid experienceId)
        {
            ViewBag.ExperienceId = experienceId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveDutiesViewModel model, Guid experienceId)
        {
            var userId = _userContext.UserId();

            var dutyProfile = Mapper.Map<DutyProfile>(model);

            await _dutyService.CreateDutyAsync(dutyProfile, experienceId);

            return RedirectToAction("Details", "Experiences", new { userId });
        }

        public async Task<IActionResult> Details(Guid experienceId)
        {
            var profiles = await _dutyService.GetDutyProfilesAsync(experienceId);

            if (profiles.IsNullOrEmpty())
            {
                return RedirectToAction("Create", new { experienceId });
            }

            return View(Mapper.Map<List<DutyProfile>>(profiles));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            await _dutyService.DeleteDutyAsync(id);
            var userId = _userContext.UserId();

            return RedirectToAction("Details", "Experiences", new { userId });
        }
    }
}

Falley/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Falley.AppService;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.ViewModel.Photos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MimeMapping;

namespace Falley.Controllers
{
    public class PhotosController : Controller
    {
        private readonly IUserContext _userContext;
        private readonly IPhotoService _photoService;

        public PhotosController(IPhotoService photoService, IUserContext userContext)
        {
            _photoService = photoService;
            _userContext = userContext;
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(List<IFormFile> files)
        {
            var userId = _userContext.UserId();

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    var photo = new PhotoProfile();
                    using (Image img = Image.FromStream(formFile.OpenReadStream()))
                    {
                        photo.FileData = img.Resize(150, 150).ToByteArray();
                    }

                    photo.FileName = formFile.FileName;

                    await _photoService.CreatePhotoAsync(photo, userId);
                }
            }

            return RedirectToAction("Details");
        }

        public async Task<IActionResult> Details()
        {
            var userId = _userContext.UserId();
            var anyPhoto = true;
            var photo = await _photoService.GetPhotoProfileAsync(userId);

            if (photo.IsNull())
            {
                anyPhoto = false;
            }

            return View(new PhotoDisplayViewModel
            {
                AnyPhoto = anyPhoto,
                UserId = userId
            });
        }

        public async Task<IActionResult> Download()
        {
            var userId = _userContext.UserId();
            var photoProfile = await _photoService.GetPhotoProfileAsync(userId);
            if (photoProfile.IsNull())
            {
                return null;
            }

            var outputStream = new MemoryStream(photoProfile.FileData);
            outputStream.Seek(0, SeekOrigin.Begin);

            return new FileStreamResult(outputStream, MimeUtility.GetMimeMapping(photoProfile.FileName));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            await _photoService.DeletePhotoAsync(id);
            return RedirectToAction("Details");
        }
    }
}

Falley/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.ViewModel.Skills;
using Microsoft.AspNetCore.Mvc;

namespace Falley.Controllers
{
    public class SkillsController : Controller
    {
        private readonly ISkillService _skillService;
        private readonly IUserContext _userContext;
        public SkillsController(ISkillService skillService, IUserContext userContext)
        {
            _skillService = skillService;
            _userContext = userContext;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveSkillViewModel model)
        {
            var userId = _userContext.UserId();
            var skillProfile = Mapper.Map<SkillProfile>(model);
            var skillId = await _skillService.CreateSkillProfileAsync(skillProfile, userId);

            return RedirectToAction("Details", new { id = userId });
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var userId = _userContext.UserId();
            var skills = await _skillService.GetSkillProfilesAsync(userId);

            if (skills.IsNullOrEmpty())
            {
                return RedirectToAction("Create");
            }

            var skillProfiles = Mapper.Map<List<SaveSkillViewModel>>(skills);

            return View(skillProfiles);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var userId = _userContext.UserId();
            await _skillService.DeleteSkillProfileAsync(id);

            return RedirectToAction("Details", new { id = userId });
        }
    }
}

Falley/Controllers/UsersController.cs
using AutoMapper;
using Falley.AppService;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.Helpers;
using Falley.ViewModel.Users;
using Microsoft.AspNetCore.Mvc;
using MimeMapping;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace Falley.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserComposerService _userComposerService;
        private readonly IPhotoService _photoService;
        private readonly IUserService _userService;
        //private readonly IViewHelper _viewHelper;
        private readonly IAccountService _accountService;

        public UsersController(
            IUserComposerService userComposerService,
            IPhotoService photoService,
            IUserService userService,
            //IViewHelper viewHelper,
            IAccountService accountService
            )
        {
            _userComposerService = userComposerService;
            _photoService = photoService;
            _userService = userService;
            //_viewHelper = viewHelper;
            _accountService = accountService;
        }

        /// <summary>
        /// get profile details of a user
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public async Task<IActionResult> Profile(Guid userId)
        {
            var userViewModel = await _userComposerService.GetUserDetailsAsync(userId);

            return View(userViewModel);
        }

        [Route("users/profiles")]
        public async Task<IActionResult> GetAllUserProfiles()
        {
            var userProfiles = await _userService.GetAllUserProiles();
            var userViewModels = Mapper.Map<List<UserDetailsUpdateViewModel>>(userProfiles);

            return Ok(userViewModels);
        }

        [HttpGet("users/{userId:guid}/details")]
        public async Task<IActionResult> Details(Guid userId)
        {
            var userProfile = await _userService.GetUserProfileAsync(userId);
            var user = Mapper.Map<UserDetailsUpdateViewModel>(userProfile);
            //var siteModel = new SiteViewHelperModel
            //{
            //    UserId = id,
            //    ViewHelper = _viewHelper
            //};

            return View(user);
        }

        [Route("users/{id:guid}/edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var userProfile = await _userService.GetUserProfileAsync(id);
            var user = Mapper.Map<UserDetailsUpdateViewModel>(userProfile);

            return View(user);
        }

        [HttpPost("users/{id:guid}/edit")]
        public async Task<IActionResult> Edit(UserDetailsUpdateViewModel model)
        {
            var userProfile = Mapper.Map<UserProfile>(model);
            await _accountService.UpdateUserProfileDetailsAsync(userProfile);
            
            return RedirectToAction("Details", new { id = model.Id });
        }
    }
}

Falley/Views/Shared/_DutyDetails.cshtml
@model IList<Falley.ViewModel.Duties.SaveDutiesViewModel>

<div>
    <h5 class="ml-3"><b>Skills</b></h5>

    @foreach (var duty in Model)
    {
        <div class="row ml-1 mb-2">
            <div class="col-4 ">
                @Html.DisplayFor(model => duty.Workdone)
            </div>
            <div class="col-2">
                @Html.ActionLink("Remove", "Delete", "Duties", new { id = duty.Id })
            </div>
        </div>
    }
</div>
@*<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>*@

Falley/Views/Shared/_Layout.cshtml
@*@model Falley.ViewModel.SiteViewHelperModel;
@using Falley.Core.IService;
@using static Falley.Core.Extensions.ObjectExtensionMethods;
@using Falley.ViewModel;

@{ 
    if (!Model.IsNull())
    {
        var viewHelper = Model.ViewHelper;
        var userContext = viewHelper.GetUserContext(Model.UserId);
    }


}*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Falley</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/bootstrap-lumen.css" />
</head>
<body>
    @*@if (!userContext.IsNull())
        {
            <header>
                <partial name="_NavBar" model="@userContext" />
            </header>
        }
        else
        {
            <header>
                <partial name="_NavBar" />
            </header>
        }*@

    <header>
        <partial name="_NavBar" />
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Falley - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Falley/Views/Shared/_NavBar.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor _httpContextAccessor;
@inject Falley.Core.IService.IUserContext _userContext;
@using static Falley.Core.Extensions.ObjectExtensionMethods;

@{
    var name = _userContext.Name();
    var userId = _userContext.UserId();

}
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Falley</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

            @if (name.IsNull())
            {
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                </ul>
            }
            else
            {
                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="LogOut">Sign Out</a>
                <div class="btn-group">
                    <button type="button" class="btn btn-default">@name</button>
                    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Profile" asp-route-userId="@userId">Resume Profile</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-userId="@userId">Details</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Resumes" asp-action="Details" asp-route-userId="@userId">Resume</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Educations" asp-action="Details" asp-route-userId="@userId">Education</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Details" asp-route-userId="@userId">Project</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Details" asp-route-userId="@userId">Skill</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Experiences" asp-action="Details" asp-route-userId="@userId">Experience</a>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Details" asp-route-userId="@userId">Photo</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Log Out</a>
                    </div>
                </div>
            }


        </div>


    </div>
</nav>