Falley/Controllers/ResumesController.cs
using AutoMapper;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.ViewModel.Resumes;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Falley.Controllers
{
    public class ResumesController : Controller
    {
        private readonly IResumeService _resumeService;
        private readonly IUserContext _userContext;
        public ResumesController(IResumeService resumeService, IUserContext userContext)
        {
            _resumeService = resumeService;
            _userContext = userContext;
        }
        [Route("users/{id:guid}/resume")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("users/{id:guid}/resume")]
        public async Task<IActionResult> Create(SaveResumeViewModel model)
        {
            var userId = _userContext.UserId();
            var resumeProfile = Mapper.Map<ResumeProfile>(model);
            
            var resumeId = await _resumeService.CreateResumeAsync(resumeProfile, userId);

            var url = String.Format("/users/{0}/resume/details", userId);

            return Redirect(url);
        }

        [HttpGet("users/{userId:guid}/resume/details")]
        public async Task<IActionResult> Details(Guid userId)
        {
            var model = await _resumeService.GetResumeProfileAsync(userId);

            if (model.IsNull())
            {
                return RedirectToAction("Create");
            }

            var resumeProfile = Mapper.Map<SaveResumeViewModel>(model);

            return View(resumeProfile);
        }

        public async Task<IActionResult> Edit(Guid userId)
        {
            var resume = await _resumeService.GetResumeProfileAsync(userId);
            var resumeView = Mapper.Map<SaveResumeViewModel>(resume);
            return View(resumeView);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaveResumeViewModel model)
        {
            var userId = _userContext.UserId();

            var resumeProfile = Mapper.Map<ResumeProfile>(model);

            await _resumeService.UpdateResumeAsync(resumeProfile, userId);

            return RedirectToAction("Details", new { userId });
        }

        public async Task<IActionResult> Delete(Guid userId)
        {
            await _resumeService.DeleteResumeAsync(userId);
            var url = String.Format("/users/{0}/resume/details", userId);

            return Redirect(url);
        }
    }
}

Falley/Views/Resumes/Create.cshtml
@model Falley.ViewModel.Resumes.SaveResumeViewModel;

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4><b>Add Resume</b></h4>

<hr />
<div class="row">
    <div class="col-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Phone Number</label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
    </form>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Falley/Views/Resumes/Details.cshtml
@model Falley.ViewModel.Resumes.SaveResumeViewModel
@inject Falley.Core.IService.IUserContext _userContext;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userId = _userContext.UserId();
}

<h4><b>Resume</b></h4>

<div>
    <hr />
    <div class="mb-4">
        <div class="col-md-8" style="background-color: cadetblue">
            <label class="control-label"><b>Description</b></label>
        </div>
        <div class="col-md-8">
            <h5> @Html.DisplayFor(model => model.Description)</h5>
        </div>
    </div>
    <div class="mb-4">
        <div class="col-md-8" style="background-color: cadetblue">
            <label class="control-label"><b>Address</b></label>
        </div>
        <div class="col-md-8">
            <h5> @Html.DisplayFor(model => model.Address)</h5>
        </div>
    </div>
    <div class="mb-4">
        <div class=" col-md-8" style="background-color: cadetblue">
            <label class="control-label"><b>Phone Number</b></label>
        </div>
        <div class="col-md-8">
            <h5> @Html.DisplayFor(model => model.PhoneNumber)</h5>
        </div>
    </div>
    <div class="mb-4">
        <div class="col-md-8" style="background-color: cadetblue">
            <label class="control-label"><b>Position</b></label>
        </div>
        <div class="col-md-8">
            <h5> @Html.DisplayFor(model => model.Position)</h5>
        </div>
    </div>
    <div class="mb-4">
        <div class="col-md-8" style="background-color:cadetblue">
            <label class="control-label"><b>Email</b></label>
        </div>
        <div class="col-md-8">
            <h5> @Html.DisplayFor(model => model.Email)</h5>
        </div>
    </div>

    <div class="mb-lg-5">
        @Html.ActionLink("Go To Edit", "Edit", "Resumes", new { userId = userId }) |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Falley/Views/Resumes/Edit.cshtml
@model Falley.ViewModel.Resumes.SaveResumeViewModel
@inject Falley.Core.IService.IUserContext _userContext;

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userId = _userContext.UserId();
}

<h4><b>Edit Resume</b></h4>

<hr />
<div class="row">
    <div class="col-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mb-lg-5">
    @Html.ActionLink("Delete", "Delete", "Resumes", new { userId = userId }) |
    @Html.ActionLink("Back To Details", "Details", "Resumes", new { userId = userId })
</div>