Falley/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Falley.Core.Extensions;
using Falley.Core.IService;
using Falley.Core.Model;
using Falley.ViewModel.Projects;
using Microsoft.AspNetCore.Mvc;

namespace Falley.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IUserContext _userContext;
        public ProjectsController(IProjectService projectService, IUserContext userContext)
        {
            _projectService = projectService;
            _userContext = userContext;
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveProjectViewModel model)
        {
            var projectProfile = Mapper.Map<ProjectProfile>(model);
            var userId = _userContext.UserId();
            await _projectService.CreateProjectAsync(projectProfile, userId);

            return RedirectToAction("Details", new { id = userId });
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var userId = _userContext.UserId();

            var projects = await _projectService.GetProjectProfiles(userId);
            if (projects.IsNullOrEmpty())
            {
                return RedirectToAction("Create");
            }
            var projectViewModel = Mapper.Map<List<SaveProjectViewModel>>(projects);

            return View(projectViewModel);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var userId = _userContext.UserId();
            await _projectService.DeleteProjectAsync(id);

            return RedirectToAction("Details", new { id = userId });
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var project = await _projectService.GetProjectProfile(id);

            var projectViewModel = Mapper.Map<SaveProjectViewModel>(project);

            return View(projectViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaveProjectViewModel model)
        {
            var userId = _userContext.UserId();
            var projectProfile = Mapper.Map<ProjectProfile>(model);
            await _projectService.UpdateProjectAsync(projectProfile, userId);

            return RedirectToAction("Details", new { id = userId });
        }
    }
}

Falley/Views/Projects/Create.cshtml
@model Falley.ViewModel.Projects.SaveProjectViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4><b>Add Project</b></h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ProjectRepository" class="control-label">Project Repository</label>
                <input asp-for="ProjectRepository" class="form-control" />
                <span asp-validation-for="ProjectRepository" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label">Project Name</label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Falley/Views/Projects/Details.cshtml
@model IList<Falley.ViewModel.Projects.SaveProjectViewModel>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4><b>Projects</b></h4>

<div>
    <hr />
    @foreach (var project in Model)
    {
        <div class="mb-2 row ml-1">
            <div class="col-md-2" style="background-color: cadetblue">
                <label class="control-label"><b>Project Repository</b></label>
            </div>
            <div class="col-md-6">
                <h5><a asp-area="" asp-action="Edit" asp-controller="Projects" asp-route-id="@project.Id">@Html.DisplayFor(model => project.ProjectRepository)</a></h5>
            </div>
        </div>
        <div class="mb-2 row ml-1">
            <div class="col-md-2" style="background-color: cadetblue">
                <label class="control-label"><b>Project Name</b></label>
            </div>
            <div class="col-md-6">
                <h5>@Html.DisplayFor(model => project.ProjectName)</h5>
            </div>
        </div>
        <hr />
    }
</div>
<div>
    <a asp-action="Index">Back to List</a> | <a asp-action="Create" asp-controller="Projects">Update Project</a>
</div>

Falley/Views/Projects/Edit.cshtml
@model Falley.ViewModel.Projects.SaveProjectViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4><a>Edit Project</a></h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ProjectRepository" class="control-label">Project Repository</label>
                <input asp-for="ProjectRepository" class="form-control" />
                <span asp-validation-for="ProjectRepository" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectName" class="control-label"> Project Name</label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Delete" asp-controller="Projects" asp-route-id="@Model.Id">Delete</a>
</div>